name: rh-rnalysis
channels:
   - nodefaults
   - conda-forge
   - bioconda
   - defaults
dependencies:
  - bioconda::samtools=1.9
  - bioconda::subread=1.6.4
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::bowtie2=2.3.5
  - bioconda::kallisto=0.45.1
  - python=3.7
  - bioconda::bioconductor-deseq2=1.22.1
  - bioconda::trim-galore=0.6.3
  - bioconda::qualimap=2.2.2a
  - bioconda::rsem=1.3.2
  - bioconda::hisat2=2.1.0
